services:
  mysql:
    image: mysql:8.0
    container_name: teacher-portrait-mysql
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teacher_portrait
      TZ: Asia/Shanghai
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-client-handshake=FALSE
      - --init-connect=SET NAMES utf8mb4
      - --skip-character-set-client-handshake
      - --default-time-zone=+08:00
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: